### ISSUE TITLE
So which standards version is it?

### ISSUE THREAD

**Issue by weavertheme** [WPTRT/theme-sniffer#101]
This plugin version, when used for WordPress-Core coding standards does not agree with the latest version of phpcs and the WordPress-Core standards installed as a standalone program on my dev site.

Which standard should be used? Seems the two should agree. Since this plugin hasn't been updated in some time, I suspect the standards have gotten out of sync. Need to know which to trust.

And, by the way, phpcbf  totally broke my code when trying to "fix" a file. It seems it left out several lines of real code. This isn't exactly relevant to this, but when one tries to use that to fix the errors in the WordPress-Core coding standard as reported by this plugin, one doesn't want code broken!

**Comment by dingo-d** [comment]
Hi! Which plugin version are you using? The 0.1.5 version is old and out of date. You should try the 1.0.0-RC1 (https://github.com/WPTRT/theme-sniffer/releases/download/1.0.0-RC1/theme-sniffer.zip). This version has the latest `phpcs` and the latest `wpcs` standards built in.

Also the plugin doesn't offer `phpcbf` capability so this is not the place to ask for this issue. I'd recommend asking it in the [WPCS](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) repo.

Aside from that, I don't like to use `phpcbf`, as it's known to break the formatting when you have deeply nested multidimensional arrays 🙂

**Comment by dingo-d** [comment]
The version 1.0.0 has been released so I'll close this issue 🙂
