### ISSUE TITLE
Whitelist editor specific theme tags

### ISSUE THREAD

**Issue by vedathemes** [WPTRT/theme-sniffer#105]
`block-styles` and `wide-blocks` are two newly approved [theme tags](https://make.wordpress.org/themes/handbook/review/required/theme-tags/). They should be whitelisted.

**Comment by timelsass** [comment]
it looks like the api call internally to fetch the tags includes them, perhaps the call is cached?

**Comment by dingo-d** [comment]
The call is cached so it could be that.

https://github.com/WPTRT/theme-sniffer/blob/feature/use-namespace/src/api/class-template-tags-request.php#L39

**Comment by dingo-d** [comment]
Should be fixed in the latest release
