### ISSUE TITLE
kirki outputted twice for textdomain sniff error message

### ISSUE THREAD

**Issue by timelsass** [WPTRT/theme-sniffer#108]
![image](https://user-images.githubusercontent.com/11907254/53614086-914f1600-3ba6-11e9-8a88-defc666b1239.png)

**Comment by dingo-d** [comment]
Hmm interesting bug. Can you provide the theme that caused it? Easier to test it.

**Comment by timelsass** [comment]
Hey it was caused because the depth of 4 in the php files loop.  I had a folder with a few classes like "class-themename-extend-kirki-typography.php", "class-themename-extend-kirki-palette.php".  The loop just kept appending kirki for found matches without checking if it existed in the array of text domains already.
