### ISSUE TITLE
Exclude JS file in sniffing

### ISSUE THREAD

**Issue by ernilambar** [WPTRT/theme-sniffer#109]
For example when there is `modernizr.min.js`, sniffer shows error `ERROR	Stylesheets must be registered/enqueued via wp_enqueue_style`

May be we need to exclude JS file from such check.

**Comment by dingo-d** [comment]
There is a checkbox to sniff only PHP files, and I'm checking for a minimised files here:

https://github.com/WPTRT/theme-sniffer/blob/ccb7bc0682c07bddccaab259d2162a846b6bc06e/src/callback/class-run-sniffer-callback.php#L376-L381

Although this is a super tricky thing to check so any sanity checking is welcomed 🙂

**Comment by dingo-d** [comment]
Fixed in the latest release
