### ISSUE TITLE
Add more specific indicators to theme name in dropdown list.

### ISSUE THREAD

**Issue by timelsass** [WPTRT/theme-sniffer#114]
Feature Request:

When using this - I often create a build zip of a final theme for distribution, deactivate my development versions and remove any hooks/filters I have and install the distribution version.  This results in me having multiple themes in the dropdown list with the same name.

I think it would be handy to have the word (Active) next to the theme name, or perhaps the version number displayed next to it.  Just something that can help identify multiple themes with the same theme name.

I realize the option is selected for the active theme, but when running multiple scans with different versions of the theme it's hard for me to keep track of.  My current solution has been to just make a temp copy of my themes directory and test versions one by one to avoid the confusion.

**Comment by dingo-d** [comment]
I could add active and version number. The themes list business logic is done in the helpers trait so it shouldn't be a problem to do 🙂 

Like the suggestion :+1:

**Comment by dingo-d** [comment]
![screenshot 2019-03-02 at 19 01 48](https://user-images.githubusercontent.com/8638515/53685639-abf7cb00-3d1d-11e9-8b0a-dc044ccc82e5.png)

Does this look good? @timelsass ?

**Comment by timelsass** [comment]
@dingo-d Yes - I like that

**Comment by dingo-d** [comment]
Ok I've pushed the changes to the PR, you can pull them. I'll close the issue 🙂
