### ISSUE TITLE
Check for required files

### ISSUE THREAD

**Issue by timelsass** [WPTRT/theme-sniffer#115]
Feature Request:

Since the theme doesn't have to be the active theme, I think we should introduce a preliminary scan of required files from the files array to provide some error feedback of missing and required files.

Some that come to mind: functions.php, style.css, readme.txt, (license{.txt|.md|})

**Comment by dingo-d** [comment]
The theme needs to have `style.css`, otherwise it will be broken (won't be shown in the list to sniff and will throw a notice in the Appearance screen). We could do a search for the minimum necessary files, this sounds reasonable (looping through all the files isn't a taxing operation in php) 🙂

**Comment by dingo-d** [comment]
This has been merged to `feature/use-namespace`.
