### ISSUE TITLE
woocommerce sniffs

### ISSUE THREAD

**Issue by timelsass** [WPTRT/theme-sniffer#116]
Feature Request:

WooCommerce is fairly common in themes - It would be nice to add additional checks for template override versions matching the latest release version of wooCommerce.  This would alert authors that they need to update their templates to the latest version.

This check could be initiated if  add_theme_support for woocommerce was found in php files.

**Comment by dingo-d** [comment]
What would we be checking for? Could that be handled by the phpcs? If so I think that [WPThemeReview](https://github.com/WPTRT/WPThemeReview) would be a better fit for this issue.

**Comment by timelsass** [comment]
Perhaps - I wasn't sure which would be the best place - I would think searching an array of template override files that themes usually provide in a theme in a /woocommerce folder.  There is a version included in the php comment of the file header, and that's compared internally in woocommerce with their version of the template.

If you think that sounds like something better handled there I can create one there

**Comment by timelsass** [comment]
yeah it seems like the check for tgmpa is included there, so it would make sense to have it in the https://github.com/WPTRT/WPThemeReview component

**Comment by joyously** [comment]
This seems out of scope. Themes shouldn't have template files that _need_ updating.
