### ISSUE TITLE
Theme prefixes check

### ISSUE THREAD

**Issue by weavertheme** [WPTRT/theme-sniffer#147]
Variables in theme templates (e.g., 404.php, archive.php, etc.) are incorrectly flagged as errors. Since these files are actually included via get_template_part(), the variables really aren't global in scope as the error implies. Perhaps a comment in the template files could silence this error for these files?

**Comment by joyously** [comment]
See https://github.com/WPTRT/WPThemeReview/issues/200
and https://github.com/WPTRT/WPThemeReview/issues/205

**Comment by dingo-d** [comment]
Closing as a duplicate plus upstream. For the globals discussion there is a #103 issue 🙂
