### ISSUE TITLE
Theme prefixes check: missing WP filters

### ISSUE THREAD

**Issue by weavertheme** [WPTRT/theme-sniffer#148]
When checking for hook names in the theme prefix check, errors are incorrectly flagged for core WP filters. E.g.,
Hook names invoked by a theme/plugin should start with the theme/plugin prefix. Found: "theme_mod_{$name}".
Hook names invoked by a theme/plugin should start with the theme/plugin prefix. Found: "the_content".

**Comment by joyously** [comment]
See https://github.com/WPTRT/theme-sniffer/issues/104
and https://github.com/WPTRT/theme-sniffer/issues/103
and https://github.com/WPTRT/WPThemeReview/issues/201

**Comment by dingo-d** [comment]
The issues have already been opened in multiple places. I'll be closing this, but do report on any odd things you may find @weavertheme :+1: 🙂
