### ISSUE TITLE
Theme sniffer is not supported by PHP 5.6?

### ISSUE THREAD

**Issue by Mariusslo** [WPTRT/theme-sniffer#161]
When trying to activate this plugin on wordpress which is on PHP5.6 I get a fatal error :
 `syntax error, unexpected ':', expecting ';' or '{' in C:\xampp5.6\htdocs\GitHub\NativeSimple\wp-content\plugins\theme-sniffer\src\class-plugin.php on line 159`

**Comment by dingo-d** [comment]
No it isn't. As noted in the readme, and on the plugin page, you need to have PHP 7.0 or higher to be able to run it.
