### ISSUE TITLE
The ignore annotations option does contrary to what it says

### ISSUE THREAD

**Issue by vladolaru** [WPTRT/theme-sniffer#164]
Right now, when the checkbox is _unchecked_ it will NOT ignore annotations and when it is _checked_ it will ignore them.

This is due to the fact that PHPCS's runner config option `annotations` is used to declare if annotations _should be taken into account_ (`true` by default), while the plugin option is opposite in declaring if they _should be ignored_ (`false` by default).

The line in question is this one: https://github.com/WPTRT/theme-sniffer/blob/development/src/callback/class-run-sniffer-callback.php#L576. We should simply negate the `$ignore_annotations` variable.

Related issue: https://github.com/WPTRT/theme-sniffer/issues/84

**Comment by dingo-d** [comment]
Thanks for the bug report, I hope to have the next version with the fix out soon 🙂

**Comment by vladolaru** [comment]
I'm glad I could help out. Keep up the great work 💪

**Comment by h71** [comment]
> Right now, when the checkbox is unchecked it will NOT ignore annotations and when it is checked it will ignore them.

It sounds correct to me. Am I missing something here?
