### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by ceylonthemes** [WPTRT/theme-sniffer#183]
Used php 7.0, 

Updated to New version from WordPress.org, Theme sniffer not starting (theme check process)

Selected check php files only.

No minified files.

**Comment by dingo-d** [comment]
Hi!

Can you give a bit more details about the bug - WP version, PHP version, debug logs, chrome dev tools errors etc.?

**Comment by ernilambar** [comment]
@ceylonthemes  Most probably there is JS error in console. Sometimes I get this also. After refresh it works. Not sure why.

**Comment by ernilambar** [comment]
Sample error https://prnt.sc/oxjrva

**Comment by ceylonthemes** [comment]
WordPress 4.9
PHP 7.0

**Comment by ceylonthemes** [comment]
Updated to WordPress 5.2.2

Change the php version 7.2

AND Check only PHP files option - Theme sniffer is Working fine
