### ISSUE TITLE
Ignore `@codingStandardsIgnore`

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/theme-sniffer#28]
Even though this will not ignore the WPCS whitelist comments, at least the PHPCS standard way to ignore code blocks can now be disabled when PHPCS is run with `--ignore-annotations`.

Unfortunately, this does require PHPCS 3.0

See https://github.com/squizlabs/PHP_CodeSniffer/issues/811#issuecomment-283538235

**Comment by jrfnl** [comment]
Also see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/862

**Comment by dingo-d** [comment]
This is related to #84 and will be added in the next release as an option (the next release is using PHPCS 3.0) 🙂

**Comment by jrfnl** [comment]
FYI: since this issue was opened, WPCS has been updated to respect the PHPCS `--ignore-annotations` directive when people use the WPCS native whitelist comments (which have been deprecated).
