### ISSUE TITLE
Overriding WordPress globals variable issue by WooCommerce

### ISSUE THREAD

**Issue by mahdiyazdani** [WPTRT/theme-sniffer#35]
Hey guys
As you may already know, WooCommerce released a new version of the plugin earlier today (Version 3.0), and they have changed almost everything in template structure and loop files.
Anyway, I just noticed NS Theme Check plugin detects an overriding WordPress globals variable issue which is caused by this line
```
setup_postdata( $GLOBALS['post'] =& $post_object );
```

https://github.com/woocommerce/woocommerce/blob/master/templates/cart/cross-sells.php

Any recommendations on this?

**Comment by grappler** [comment]
Issue created upstream https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/913

**Comment by dingo-d** [comment]
I'll close this as it's an upstream issue
