### ISSUE TITLE
Rename plugin

### ISSUE THREAD

**Issue by ernilambar** [WPTRT/theme-sniffer#56]
Rename plugin to `Theme Sniffer`.

**Comment by dingo-d** [comment]
Will the repo name be changed to `theme-check` as well?

**Comment by ernilambar** [comment]
Yes, repo will also be renamed to `theme-sniffer`.

**Comment by dingo-d** [comment]
I added a PR that changes the name of the plugin. Tested it on my local vagrant installation, works fine. https://github.com/WPTRT/ns-theme-check/pull/57

I also added some minor js fixes in the `admin.js`

**Comment by ernilambar** [comment]
Fixed https://github.com/WPTRT/theme-sniffer/pull/57
