### ISSUE TITLE
Consider how output is used

### ISSUE THREAD

**Issue by joyously** [WPTRT/theme-sniffer#58]
The plugin's output is normally displayed to the local user, and this use looks fine, although it would be nice to truncate the file path to start with the wp-content folder (like Debug Bar does for errors) or the theme folder (since this is our main concern).
However, the raw output is often copied and pasted by the reviewer into Trac tickets where Wikiformatting expands it quite a lot if it is not put in a preformat block. For this reason, can some of the output be modified to use less space and fewer things that are expanded in Wikiformatting? Or perhaps surround it with the preformat block markings?
Specifically, the lines of dashes cause a lot of the expansion, as well as the lines listing errors since they start with a blank. Here's a screenshot showing how just a few lines of raw output grow. 
![raw-output-expands](https://user-images.githubusercontent.com/7957680/26946869-4f49999c-4c56-11e7-8d06-c5f312ccb354.jpg)

**Comment by dingo-d** [comment]
The theme check output shouldn't be pasted directly in the trac ticket. First of all, it should be examined to see what is actually the issue, and what isn't. And secondly when pasting any code one should use proper code tags. In this case surrounding the report with 

```
{{{
sniffs go here
}}}
```

would keep it readable.

We should put in the handbook that raw theme check shouldn't be pasted in the ticket.

**Comment by grappler** [comment]
> although it would be nice to truncate the file path

We do this in the default view. It is a bit more work in the raw output as we would need to run a search and replace on the whole text.


The problem with the preview can be fixed by putting it in a preformat block. e.g.
```
{{{

}}}
```

The reviewer can see how the content is being outputted like in your screenshot and can edit it.

**Comment by joyously** [comment]
If I can find the tickets where this was done, I'll put them here, but it's obvious that someone _can_ format themselves, but that doesn't mean that they will.
If a few tweaks are made, it wouldn't matter if they use a preformat block or not.  Or if the raw output contains the preformat block, it would save them the trouble. But as mentioned, they aren't supposed to just paste the whole thing in there anyway. One I saw recently was quite long as raw, with lots of errors, and it was huge due to the WikiFormatting applied.

**Comment by dingo-d** [comment]
Yeah, I think by modifying the output here wouldn't solve the problem of pasting it in the ticket. We should add this in the handbook that the sniffer results shouldn't be pasted in the ticket, better to solve it at the root of the problem ;)

**Comment by dingo-d** [comment]
I've referenced this issue in the to do spreadsheet I made for the projects the theme review team is doing, and this should be added in the handbook, once the handbook gets a bit of a revamp 🙂
