### ISSUE TITLE
Introduce Namespacing

### ISSUE THREAD

**Issue by grappler** [WPTRT/theme-sniffer#61]
As the composer autoloader uses namespaces and that requires PHP 5.3 then we may just as well use namespaces too.

This is also a developer tool so developers should know how to change the PHP version of their development environment.

PR welcome.

**Comment by ernilambar** [comment]
I guess this would be big PR as whole plugin architecture will be changed.

**Comment by dingo-d** [comment]
Open PR for the refactor #97

**Comment by dingo-d** [comment]
Fixed in the latest release.
