### ISSUE TITLE
Include package-lock.json file

### ISSUE THREAD

**Issue by dingo-d** [WPTRT/theme-sniffer#68]
When you build the plugin with new node (ver 8), `package-lock.json` file is created. 

We should either include this in the repo, or put it in the .gitignore file.

**Comment by grappler** [comment]
I would include it like we do with composer.

**Comment by dingo-d** [comment]
Both are added with the new version :)

**Comment by joyously** [comment]
Does this apply?
https://netweb.blog/2018/01/26/lockfiles-breaks-semantic-versioning/

**Comment by dingo-d** [comment]
Hmmm interesting read. I can add an update command that will run [`npm-check-updates`](https://www.npmjs.com/package/npm-check-updates) command prior to any release. This will ensure that all the packages are up to date. Plus we do test the plugin before release and would notice if anything is breaking.
Plus we are essentially creating an _app_. We're not putting theme sniffer plugin on packagist to be used via composer, or on npm repository to be used with npm/yarn.
