### ISSUE TITLE
Check for use of site_url()

### ISSUE THREAD

**Issue by joyously** [WPTRT/theme-sniffer#72]
What do you think about a Warning for using `site_url()` instead of `home_url()`? 
I'm trying to think if a theme would ever need to use `site_url`, and can't think of any reason.

I have encountered several themes that have used `site_url` for a link to 'Home' (like on the 404 page), but in a subdirectory install, that is the wrong address. One even used it for the Search, which gave me a 404.

**Comment by dingo-d** [comment]
Maybe this should be added as a sniff in the `WordPress-Theme` standard?

**Comment by dingo-d** [comment]
I'll close this as this should be in the [WPThemeReview](https://github.com/WPTRT/WPThemeReview/) so that the rule is sniffed using PHPCS.

See if there is an opened issue in the standards, and if there isn't can you please open a new issue and add bunch of code examples @joyously? Thanks!

**Comment by joyously** [comment]
I can't keep up with which repo is "standards" and what you are asking me to do. If there's already Justin's issue, do you need another?

**Comment by dingo-d** [comment]
This is the repo of the plugin, and the `WPThemeReview` are the standards. If there is a proposal for this kind of sniff then you can post code comments there (if you have them) 🙂
