### ISSUE TITLE
Distribution too large

### ISSUE THREAD

**Issue by tradesouthwest** [WPTRT/theme-sniffer#76]
When I upload the distribution plugin zip, WP reports the file is too large to upload. I saw no other version or install instructions on how to rework the zip into a smaller zip. 

`
* Version:           0.1.4

* Download [zip file](https://github.com/ernilambar/ns-theme-check/releases/download/0.1.4/ns-theme-check.0.1.4.zip). [Note: Please use this distribution plugin zip. GitHub provided zip will not work.]
* Install this as you normally install a WordPress plugin
* Activate plugin
`

**Comment by dingo-d** [comment]
What is your upload limit? The zip file is 7.4MB, this means that your limit is lower than this.
You should change this in `php.ini` file.

**Comment by tradesouthwest** [comment]
The WP uploader returned the size error/message. ini is set plenty high. You can close this. I used version 0.1.2 and it loaded like a charm.

**Comment by tradesouthwest** [comment]
0.1.2 is only  939K. I was hoping I missed something in the 0.1.4 version and did not need to upload the whole thing (7.4MB is a far cry from 1MB)???

**Comment by pattonwebz** [comment]
Hey @tradesouthwest The latest release zip contains the entire node_modules directory. That folder is only needed in development and isn't needed to run the plugin in WP. If you delete that folder from inside the archive it will be around 1MB and a lot easier to upload :)

**Comment by dingo-d** [comment]
We will need to fix the release, but we have some updating to do first...

**Comment by pattonwebz** [comment]
Yup, more updates before new release makes sense :)

**Comment by dingo-d** [comment]
The new release is smaller, but still 4.8 MB due to vendors folder (node_modules were removed, but vendors are necessary for the plugin to work properly iirc).
I'll close this for now, if you have any suggestions for improvement please open a new issue :)

**Comment by tradesouthwest** [comment]
Woo Hoo! you rock.... maybe if there were a notation... if the [was] I missed it. Good to know about dev. Maybe releasing a "non-dev" ver....?

**Comment by dingo-d** [comment]
Not sure I understand exactly about non dev version? There is a "non dev" version in the zip file in the readme :D That is the compiled and ready to use plugin without the `node_modules` folder :) I'll do another release soon with even more improvements :)
