### ISSUE TITLE
Unable to find Sanitize Callback Function missing on customizer API

### ISSUE THREAD

**Issue by kafleg** [WPTRT/theme-sniffer#82]
While uploading themes on .org, if Sanitize Function is missing, it shows **Required: Found a customizer setting that did not have a sanitize function.**  But if we check theme with this plugin, we can't get this error.

**Comment by dingo-d** [comment]
The theme checker on wordpress.org is this one: https://wordpress.org/plugins/theme-check/

The repo for it should be located here: https://github.com/WordPress/theme-check so you can try to check if the issue exists there.

Also which coding standard are you using when sniffing the theme?

**Comment by kafleg** [comment]
Hello @dingo-d,
Yes, i got the error on Theme Check plugin. I just posted issues here for Theme Sniffer. I think we are planning to implement this plugin on .org so better to add missing things to this plugin as well. 

Thank you

**Comment by dingo-d** [comment]
With Tide coming I'm not sure what is the status of Theme Sniffer. I'll continue working on it in my spare time, and we could add it on plugin repo eventually :)

**Comment by dingo-d** [comment]
Closed due to inactivity
