### ISSUE TITLE
Umm, plugin support?

### ISSUE THREAD

**Issue by dovy** [WPTRT/theme-sniffer#85]
Love this idea since theme-check could use more checks.

I see no reason why this can't work for a plugin. Care to make that happen?

**Comment by joyously** [comment]
See https://github.com/jrfnl/QA-WP-Projects for Juliette's code to go with her talk on exactly that.
Talk: https://speakerdeck.com/jrf/leveraging-the-wordpress-coding-standards-to-review-plugins-and-themes-1

**Comment by dingo-d** [comment]
One of the things I can also see where this could be an issue is that plugins can be written in a variety of ways, using different coding standards (not necessarily WPCS, but PSR for instance). So we would have to include those or even allow the addition of custom rulesets in the plugin.

**Comment by dingo-d** [comment]
I'll close this, as there is not much of activity around this issue. Plus I think once we release a new version, a fork could be made that will be for plugin checking (`plugin-sniffer` maybe).
