### ISSUE TITLE
After running the plugin, it shows up warnings and a notice

### ISSUE THREAD

**Issue by bilal-pp** [WPTRT/theme-sniffer#86]
Hi,

After selecting the theme name from the drop-down and clicking on the go button, I get the the following

Notice: tempnam(): file created in the system's temporary directory in /Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php on line 177

Warning: fopen(): Filename cannot be empty in /Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php on line 177

Warning: fwrite() expects parameter 1 to be resource, boolean given in /Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php on line 183

Warning: stream_get_meta_data() expects parameter 1 to be resource, boolean given in /Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php on line 242

Warning: file_get_contents(): Filename cannot be empty in /Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php on line 244

Warning: fclose() expects parameter 1 to be resource, boolean given in /Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php on line 245
Time: 25399106 mins, 9.16 secs; Memory: 16Mb
Also I am attaching the screenshot of the selected standards and options. Please note I am running the plugin on my localhost (XAMPP).

Thanks,
Bilal Ahmed
![screen shot 2018-04-17 at 12 04 33 pm](https://user-images.githubusercontent.com/20988725/38853009-8a7cb6b4-4239-11e8-8016-d60f40610ff9.png)

**Comment by bilal-pp** [comment]
I am using the version linked in the readme.
![screen shot 2018-04-17 at 12 32 23 pm](https://user-images.githubusercontent.com/20988725/38853599-6e509ec2-423b-11e8-9986-d2a7a18f06d7.png)

**Comment by dingo-d** [comment]
Hi!

The plugin should work even on local development. What PHP version are you using on XAMPP?

**Comment by bilal-pp** [comment]
Hi @dingo-d 

PHP version on my XAMPP is 7.2. I've also tried the plugin on version 5.5, results are still the same.

**Comment by dingo-d** [comment]
Please check that you have write permissions on the `wp-content` folder (and subfolders).

**Comment by bilal-pp** [comment]
Hi,

Checked for the permissions, its fine. But still after running the plugin, I get the same errors.

**Comment by dingo-d** [comment]
Can you try the older version of the plugin and see if the same error will occur?

https://github.com/WPTRT/theme-sniffer/releases/download/0.1.4/ns-theme-check.0.1.4.zip

**Comment by bilal-pp** [comment]
Hi @dingo-d,

It seems to work. Please check the screenshot.

Thanks

![screen shot 2018-04-17 at 2 36 34 pm](https://user-images.githubusercontent.com/20988725/38860113-0e9925b4-424d-11e8-9761-6ffd4d42be79.png)

**Comment by bilal-pp** [comment]
And one more thing, could you please fix the issues in the newer version.

Thanks

**Comment by dingo-d** [comment]
The thing is, I tested 0.1.5 version and it worked just like version 0.1.4 for me (and since people are using it I guess it works for them too).

Can you choose Twenty Seventeen theme and see what output do you get out with new and old version.

For me, the version 0.1.5 looked like this
![screen shot 2018-04-17 at 11 59 10](https://user-images.githubusercontent.com/8638515/38863035-cb15846a-4236-11e8-8cef-9798aebdff58.png)

**Comment by bilal-pp** [comment]
Hi @dingo-d ,

I used Twenty Seventeen theme and checked using both the plugins (old and new) and there are no changes. Attaching the screenshot.

Could you please let me know what are the system requirements for this plugin.

![screen shot 2018-04-17 at 3 33 46 pm](https://user-images.githubusercontent.com/20988725/38863470-5a08ac56-4255-11e8-8ba3-fea10bb1eff8.png)
![screen shot 2018-04-17 at 3 32 30 pm](https://user-images.githubusercontent.com/20988725/38863500-70f3c338-4255-11e8-8cf5-d5d6d1c49a38.png)

**Comment by dingo-d** [comment]
The latest should work with:

```md
Requires at least: 4.4
Tested up to: 4.9.2
Requires PHP: 5.3
```

My guess is that something is not ok with your XAMPP setup. I recommend using [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/) for wp development.

**Comment by dingo-d** [comment]
Closed due to inactivity
