### ISSUE TITLE
How to fix this warning? Its wordpress function

### ISSUE THREAD

**Issue by abdulmomin-dev** [WPTRT/theme-sniffer#88]
WARNING	Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'paginate_links'

I use this in my theme
`
              echo paginate_links( array(
                    'prev_text' => '<i class="fa fa-angle-left" aria-hidden="true"></i>',
                    'next_text' => '<i class="fa fa-angle-right" aria-hidden="true"></i>',
                ) ); `

**Comment by ernilambar** [comment]
First thing, not all warnings are necessary to be fixed. You need to check manually whether it needs to be fixed or not.
Second thing is that, do not use `paginate_links()`. Use `the_posts_pagination()` instead.

**Comment by abdulmomin-dev** [comment]
Thanks @ernilambar  its work fine.
