### ISSUE TITLE
Local Development for PHP 7.2

### ISSUE THREAD

**Issue by benlumia007** [WPTRT/theme-sniffer#90]
Apparently VVV upgraded their PHP to 7.2 and getting the following deprecated 

```
<b>Deprecated</b>:  Function create_function() is deprecated in <b>/srv/www/getbenonit/public_html/wp-content/plugins/theme-sniffer/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php</b> on line <b>93</b><br />
```

**Comment by dingo-d** [comment]
This seems like an upstream issue with the [WordPress Coding Standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) (`vendor/wp-coding-standards/wpcs/WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php`). 

Can you open an issue there?
