### ISSUE TITLE
Spaces must be used to indent lines; tabs are not allowed

### ISSUE THREAD

**Issue by siddhartha10jun** [WPTRT/theme-sniffer#92]
"Tabs must be used to indent lines; spaces are not allowed" this issue not solve by this script

**Comment by dingo-d** [comment]
Can you elaborate a bit more where this error happens and why?

**Comment by siddhartha10jun** [comment]
Many error find by theme sniffer plugin example:(https://www.screencast.com/t/8rFPDyeB)
i attached a screen shot they help to understand it whats is an issue. 
My issues is i fix many theme sniffer plugin error manually and after i find this script and this script for automatically remove error but i run this script and my fix error revert it...

**Comment by dingo-d** [comment]
You probably used `phpcbf` with a wrong ruleset applied. Please read how to use the PHP_CodeSniffer: https://github.com/squizlabs/PHP_CodeSniffer/wiki, and for the WordPress Coding Standards: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki

You should use the same ruleset for sniffing `phpcs` and for fixing the errors with `phpcbf`.
