### ISSUE TITLE
Displaying error and not telling the line

### ISSUE THREAD

**Issue by fabianobn** [WPTRT/theme-sniffer#93]
Hello, I'm performing the verification of my theme, however the plugin is returning me Error and does not show me where.

![captura de tela de 2018-09-26 16-31-11](https://user-images.githubusercontent.com/5238462/46104464-c693aa00-c1a9-11e8-8c05-81f94ec5c21a.png)
![captura de tela de 2018-09-26 16-31-28](https://user-images.githubusercontent.com/5238462/46104467-c693aa00-c1a9-11e8-9813-7d4a591c4821.png)
![captura de tela de 2018-09-26 16-31-55](https://user-images.githubusercontent.com/5238462/46104468-c693aa00-c1a9-11e8-9994-2b7c049b7434.png)

**Comment by dingo-d** [comment]
This is the latest version? And did you use a zip file?

The screenshot in the readme is what your results should look like - a header with the file name, and the numbers on the side mark the line in the file where the issue is.

**Comment by fabianobn** [comment]
yes is the last version.... I clone the git reposiitory!

**Comment by dingo-d** [comment]
Ok, can you download the zip file: https://github.com/WPTRT/theme-sniffer/releases/download/0.1.5/theme-sniffer.0.1.5.zip and test again?

**Comment by fabianobn** [comment]
yes.... moment!

**Comment by fabianobn** [comment]
Thanks man!!! Fixed!

**Comment by dingo-d** [comment]
:) Happy to help
