### ISSUE TITLE
Theme Sniffer not working

### ISSUE THREAD

**Issue by davy440** [WPTRT/theme-sniffer#94]
When I try to scan a theme, it does not scan and instead an error message -
**_Check has failed :( Percent completed:

All done!_**
Any help would be appreciated.

**Comment by dingo-d** [comment]
Did you use the release or did you just download the github repo?

https://github.com/WPTRT/theme-sniffer/releases/download/0.1.5/theme-sniffer.0.1.5.zip

If v 0.1.5 is not working, try with https://github.com/WPTRT/theme-sniffer/releases/download/0.1.4/ns-theme-check.0.1.4.zip

The plugin is currently going through a massive rewrite so you'll have to wait for the new version a bit.

**Comment by dingo-d** [comment]
Here's the update on the progress

https://make.wordpress.org/themes/2019/01/14/development-help-with-theme-sniffer/

Closing the issue.
