### ISSUE TITLE
Add list of allowed licenses in the style.css

### ISSUE THREAD

**Issue by dingo-d** [WPTRT/theme-sniffer#98]
Since I can parse `style.css`, and could probably parse `readme.txt` in the theme, it could be a good feature to have License checks to see if the specified license is in line with GPL.

I'd need a list of allowed Licenses so that I can check agains them 🙂

**Comment by DannyCooper** [comment]
This list is a good start - https://make.wordpress.org/themes/handbook/review/resources/#licenses-bundled-resources

Can we add a blacklist check for these? 

`unsplash.com, sxc.hu, photopin.com, publicdomainpictures.net, splitshire.com,  pixabay.com`

**Comment by dingo-d** [comment]
Sure that could be added as well, whitelist and blacklist 🙂

**Comment by DannyCooper** [comment]
Blacklist alone would cut my review time in half 🔥

**Comment by timelsass** [comment]
https://github.com/WPTRT/theme-sniffer/pull/139 works with the readme.txt, and dives into license validation for the primary License added.  @DannyCooper I [added your blacklisted names](https://github.com/WPTRT/theme-sniffer/pull/139/commits/106ae5083eacadc112776de5349f90c1acfb3540#diff-842fe75944c1e6909eed78bfa7007a56R177) in preparation for the resources section, but haven't implemented them for that section yet.

**Comment by KestutisIT** [comment]
I just wanted to be sure that none of them will be missed - GPLv3, AGPLv3 and MIT. As we use all 3 for different projects / scopes :).

**Comment by dingo-d** [comment]
I'll close this because #139 has been merged. We'll work further on this (refactor the licenses to be pulled from a repo etc.).
