### ISSUE TITLE
PHP fatal error in plugin activation

### ISSUE THREAD

**Issue by ernilambar** [WPTRT/theme-sniffer#99]
Fatal error: Uncaught TypeError: Return value of Theme_Sniffer\Assets\Assets_Handler::add() must be an instance of Theme_Sniffer\Assets\void, none returned in /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/assets/class-assets-handler.php:35 Stack trace: #0 /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/assets/assets-awareness-trait.php(41): Theme_Sniffer\Assets\Assets_Handler->add(Object(Theme_Sniffer\Assets\Script_Asset)) #1 /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/admin-menus/class-base-admin-menu.php(33): Theme_Sniffer\Admin_Menus\Base_Admin_Menu->register_assets() #2 /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/class-plugin.php(136): Theme_Sniffer\Admin_Menus\Base_Admin_Menu->register() #3 [internal function]: Theme_Sniffer\Core\Plugin->Theme_Sniffer\Core\{closure}(Object(Theme_Sniffer\Admin_Menus\Sniff_Page), 1) #4 /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/class-plugin.php(137): array_walk(Array, in /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/assets/class-assets-handler.php on line 35

**Comment by ernilambar** [comment]
I was testing https://github.com/WPTRT/theme-sniffer/releases/tag/0.2.0-RC1

**Comment by dingo-d** [comment]
I've updated the zip file, can you try again?

Thanks 🙂

**Comment by ernilambar** [comment]
In the latest zip, I get following.
`Fatal error: Uncaught TypeError: Argument 2 passed to Theme_Sniffer\Assets\Base_Asset::deferred_action() must be an instance of Theme_Sniffer\Assets\Closure, instance of Closure given, called in /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/assets/class-base-asset.php on line 48 and defined in /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/assets/class-base-asset.php:74 Stack trace: #0 /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/assets/class-base-asset.php(48): Theme_Sniffer\Assets\Base_Asset->deferred_action('admin_enqueue_s...', Object(Closure), 1) #1 /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/assets/class-assets-handler.php(44): Theme_Sniffer\Assets\Base_Asset->register() #2 /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/class-plugin.php(145): Theme_Sniffer\Assets\Assets_Handler->register() #3 /var/www/review.dev/public_html/wp-includes/class-wp-hook.php(286): Theme_Sniffer\Core\Plugin->register_assets_ in /var/www/review.dev/public_html/wp-content/plugins/theme-sniffer/src/assets/class-base-asset.php on line 74`

**Comment by dingo-d** [comment]
Oh crap, I've removed the `use Closure`at the top 😬 On it! 😄

**Comment by ernilambar** [comment]
Ok, no fatal error. Is `Hide Warnings` checkbox working?

**Comment by dingo-d** [comment]
Nope, I'm having issues with that 😕 The new sniffing process is different than the old one so I have to create my own sniff runner

https://github.com/WPTRT/theme-sniffer/blob/feature/use-namespace/src/callback/class-run-sniffer-callback.php#L395

And there something is behaving odd...

**Comment by ernilambar** [comment]
Ok, closing this issue for now.

**Comment by dingo-d** [comment]
If you find any more issues let me know 🙂
